REDIS_HOST = 'localhost'
REDIS_PORT = 6379

WIDTH, HEIGHT = 512, 512
NPLAYERS = 20_000
# NPLAYERS = 10_000
# NPLAYERS = 1000
WINDOW_WIDTH = 32
# WINDOW_WIDTH = 100

PLAYERS_BY_X = "players:by_x"
PLAYERS_BY_Y = "players:by_y"
TASKS_LIST_TPL = "tasks:{}"

# LOGGING_LEVEL = "DEBUG"
LOGGING_LEVEL = "INFO"

GENERATE_TASKS_EVERY_X_SECONDS = 5
PAGE_REFRESH_RATE = 1